# Platform Labels
- name: "platform: linux"
  color: "FFA500"
  description: "Issues or PRs related to Linux platform"

- name: "platform: windows"
  color: "0078D7"
  description: "Issues or PRs related to Windows platform"

- name: "platform: macos"
  color: "000000"
  description: "Issues or PRs related to macOS platform"

- name: "platform: cross-platform"
  color: "7CFC00"
  description: "Issues or PRs affecting multiple platforms"

# Type Labels
- name: "type: bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "type: enhancement"
  color: "a2eeef"
  description: "New feature or request"

- name: "type: documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: "type: question"
  color: "d876e3"
  description: "Further information is requested"

- name: "type: performance"
  color: "fbca04"
  description: "Performance improvements"

# Component Labels
- name: "component: vulkan"
  color: "AC162C"
  description: "Related to Vulkan rendering"

- name: "component: opengl"
  color: "5319E7"
  description: "Related to OpenGL rendering"

- name: "component: editor"
  color: "1d76db"
  description: "Related to the editor layer"

- name: "component: scripting"
  color: "000080"
  description: "Related to Lua scripting system"

- name: "component: physics"
  color: "006b75"
  description: "Related to physics system (Bullet)"

- name: "component: particles"
  color: "bfd4f2"
  description: "Related to particle system"

# Priority Labels
- name: "priority: critical"
  color: "b60205"
  description: "Critical priority"

- name: "priority: high"
  color: "d93f0b"
  description: "High priority"

- name: "priority: medium"
  color: "fbca04"
  description: "Medium priority"

- name: "priority: low"
  color: "0e8a16"
  description: "Low priority"

# Status Labels
- name: "status: needs-investigation"
  color: "fef2c0"
  description: "Needs further investigation"

- name: "status: in-progress"
  color: "c2e0c6"
  description: "Currently being worked on"

- name: "status: blocked"
  color: "d93f0b"
  description: "Blocked by another issue"

- name: "status: wontfix"
  color: "ffffff"
  description: "This will not be worked on"

# Good First Issue
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

# Dependencies
- name: "dependencies"
  color: "0366d6"
  description: "Pull requests that update a dependency file"
