#version 450

layout (local_size_x = 16, local_size_y = 16) in;
layout (binding = 0, rgba8) uniform readonly image2D inputImage;
layout (binding = 1, rgba8) uniform writeonly image2D outputImage;

void main()
{
    vec3 rgb = imageLoad(inputImage, ivec2(gl_GlobalInvocationID.xy)).rgb;

    vec3 invert = vec3(1.0f) - rgb;
    imageStore(outputImage, ivec2(gl_GlobalInvocationID.xy), vec4(invert, 1.0f));
}
